/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...path]': RouteRecordInfo<'/[...path]', '/:path(.*)', { path: ParamValue<true> }, { path: ParamValue<false> }>,
    '/404': RouteRecordInfo<'/404', '/404', Record<never, never>, Record<never, never>>,
    '/about/': RouteRecordInfo<'/about/', '/about', Record<never, never>, Record<never, never>>,
    '/about/site': RouteRecordInfo<'/about/site', '/about/site', Record<never, never>, Record<never, never>>,
    '/albums/': RouteRecordInfo<'/albums/', '/albums', Record<never, never>, Record<never, never>>,
    '/albums/bh3': RouteRecordInfo<'/albums/bh3', '/albums/bh3', Record<never, never>, Record<never, never>>,
    '/albums/gallery': RouteRecordInfo<'/albums/gallery', '/albums/gallery', Record<never, never>, Record<never, never>>,
    '/archives/': RouteRecordInfo<'/archives/', '/archives', Record<never, never>, Record<never, never>>,
    '/categories/': RouteRecordInfo<'/categories/', '/categories', Record<never, never>, Record<never, never>>,
    '/girls/': RouteRecordInfo<'/girls/', '/girls', Record<never, never>, Record<never, never>>,
    '/links/': RouteRecordInfo<'/links/', '/links', Record<never, never>, Record<never, never>>,
    '/page/[page]': RouteRecordInfo<'/page/[page]', '/page/:page', { page: ParamValue<true> }, { page: ParamValue<false> }>,
    '/posts/': RouteRecordInfo<'/posts/', '/posts', Record<never, never>, Record<never, never>>,
    '/posts/0': RouteRecordInfo<'/posts/0', '/posts/0', Record<never, never>, Record<never, never>>,
    '/posts/申论/文章写作': RouteRecordInfo<'/posts/申论/文章写作', '/posts/申论/文章写作', Record<never, never>, Record<never, never>>,
    '/posts/hi': RouteRecordInfo<'/posts/hi', '/posts/hi', Record<never, never>, Record<never, never>>,
    '/posts/mihoyo/bh3': RouteRecordInfo<'/posts/mihoyo/bh3', '/posts/mihoyo/bh3', Record<never, never>, Record<never, never>>,
    '/posts/mihoyo/sr': RouteRecordInfo<'/posts/mihoyo/sr', '/posts/mihoyo/sr', Record<never, never>, Record<never, never>>,
    '/posts/mihoyo/ys': RouteRecordInfo<'/posts/mihoyo/ys', '/posts/mihoyo/ys', Record<never, never>, Record<never, never>>,
    '/posts/mihoyo/zzz': RouteRecordInfo<'/posts/mihoyo/zzz', '/posts/mihoyo/zzz', Record<never, never>, Record<never, never>>,
    '/tags/': RouteRecordInfo<'/tags/', '/tags', Record<never, never>, Record<never, never>>,
  }
}
